# This is the pod monitor for the job ingestion producer
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: dummy-ingester-scraper
    scrape-by: cluster-grafana-agent
  name: dummy-ingester-podmonitor
spec:
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      run: {{ .Values.deployment.name }}
